#kingdee credentials
#Tue Oct 28 08:28:21 CST 2025
kingdee.appKey=7EH5RtzN
kingdee.appSecret=3b41ef894ddf82a19436c595bed5681c5d7e70b3
kingdee.baseUrl=https\://api.kingdee.com
kingdee.clientId=237115
kingdee.clientSecret=4001af3dafd9256468ea55909ed68ee7
kingdee.routerAddr=https\://tf.jdy.com
kingdee.tokenPath=/jdyconnector/app_management/kingdee_auth_token
kingdee.tokenRefreshBufferSeconds=300
